spring:
  application:
    name: MadrasCheck
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: postgres
    password: test
    url: jdbc:postgresql://localhost:5432/madras